USE codeup_test_db;
DROP TABLE IF EXISTS albums;

CREATE TABLE IF NOT EXISTS albums (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
artist VARCHAR(45) NOT NULL,
name VARCHAR(100) NOT NULL DEFAULT 'Untitled',
release_date INT UNSIGNED,
sales FLOAT,
genre VARCHAR(30),
PRIMARY KEY (id)
);
SHOW TABLES;